name: "Release"

on:
  workflow_dispatch:
    inputs:
      dry-run-semantic-release:
        type: boolean
        description: Dry-run semantic-release
        default: false
      with-docker-images:
        type: boolean
        description: Build and push docker images
        default: true

jobs:
  build-docker-image:
    if: ${{ github.event.inputs.with-docker-images == 'true' }}
    name: Build and push docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: git pull

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          labels: |
            org.opencontainers.image.version=main
            org.opencontainers.image.revision=a2b57d026f10b2e4827bdb4d164de9ec742072f2
          images: |
            ghcr.io/jorenn92/maintainerr

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Build & Push docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            GIT_SHA=a2b57d026f10b2e4827bdb4d164de9ec742072f2
            VERSION_TAG=stable
          tags: |
            ghcr.io/jorenn92/maintainerr:2.7.0
            ghcr.io/jorenn92/maintainerr:latest
            jorenn92/maintainerr:2.7.0
            jorenn92/maintainerr:latest
          labels: ${{ steps.meta.outputs.labels }}
